version: '2'
services:
    jhipstersabrina-app:
        image: jhipstersabrina
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstersabrina-postgresql:5432/jhipsterSabrina
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersabrina-postgresql:
        extends:
            file: postgresql.yml
            service: jhipstersabrina-postgresql
